[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#0066CC"
backgroundColor = "#EBF5FB"
secondaryBackgroundColor = "#D6EAF8"
textColor = "#1A2D4C"
font = "sans serif"

[browser]
gatherUsageStats = false
